### ISSUE TITLE
[Question] Why would testcontainers fail to create docker network under non-root user

### ISSUE THREAD

**Issue by ivankovnatsky** [testcontainers/testcontainers-rs#507]
Hello, thanks for the crate.

We're trying to migrate our pipeline to use only non-privileged users, and we're getting:

```

---- test_set stdout ----
thread 'test_set' panicked at 'failed to create docker network', /home/user/.cargo/git/checkouts/testcontainers-rs-afc9a8ab8422234e/c4c98b1/testcontainers/src/clients/cli.rs:210:9
stack backtrace:
   0:     0x55595161192a - std::backtrace_rs::backtrace::libunwind::trace::ha271a8a7e1f3d4ef
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55595161192a - std::backtrace_rs::backtrace::trace_unsynchronized::h85739da0352c791a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55595161192a - std::sys_common::backtrace::_print_fmt::hbc6ebcfb2910b329                
```

I've tried to debug myself, but I'm not really an expert in rust. Tried to create arbitrary docker network using a common cli on CI runner itself, and it worked without a problem, using non-root user.

Do you maybe know why would it fail?

Thanks.

**Comment by thomaseizinger** [comment]
> Do you maybe know why would it fail?

Can't think of anything either, sorry.
